const defaultStyleMap = [
  /* Caracteres */
  "r[style-name='Default Paragraph Font'] => p.DefaultParagraphFont",
  "r[style-name='destaqueCaixaAlta'] => p.destaqueCaixaAlta",
  "r[style-name='italico'] => em.italico",
  "r[style-name='negrito'] => strong.negrito",
  "r[style-name='realceAmarelo'] => p.realceAmarelo",
  "r[style-name='realceAzul'] => p.realceAzul",
  "r[style-name='realceRosa'] => p.realceRosa",
  "r[style-name='realceTurquesa'] => p.realceTurquesa",
  "r[style-name='realceVerde'] => p.realceVerde",
  "r[style-name='realceVermelho'] => p.realceVermelho",
  "r[style-name='termoGossario'] => dl.termoGossario > dt",
  "r[style-name='textoColorido'] => p.textoColorido",

  /* Paragrafos */
  "p[style-name='Heading 1'] => h1.Heading1:fresh",
  "p[style-name='Normal'] => p.Normal > li:fresh",
  "p[style-name='comentario'] => !",
  "p[style-name='listaAlfabetica'] => ol.listaAlfabetica > li:fresh",
  "p[style-name='listaBullets'] => ul.listaBullets > li:fresh",
  "p[style-name='listaNumerica'] => ol.listaNumerica > li:fresh",
  "p[style-name='listaRomana'] => ol.listaRomana > li:fresh",
  "p[style-name='sublinhado'] => u.sublinhado:fresh",
  "p[style-name='titulo2'] => h2.titulo2:fresh",
  "p[style-name='titulo3'] => h3.titulo3:fresh",
  "p[style-name='titulo4'] => h4.titulo4:fresh",
  "p[style-name='tituloAula'] => h3.tituloAula:fresh",
  "p[style-name='tituloH4'] => h4.tituloH4:fresh",
  "p[style-name='tituloH5'] => h5.tituloH5:fresh",
  "p[style-name='tituloH6'] => h6.tituloH6:fresh",

  /* Tabelas */
  "table[style-name='Grid Table 5 Dark Accent 5'] => table.GridTable5DarkAccent5",
  "table[style-name='accordion'] => table.accordion",
  "table[style-name='boxDestaque'] => table.boxDestaque",
  "table[style-name='boxLembrete'] => table.boxLembrete",
  "table[style-name='citacao'] => table.citacao",
  "table[style-name='estruturaPedagogica'] => table.estruturaPedagogica",
  "table[style-name='midiaAudio'] => table.midiaAudio",
  "table[style-name='midiaImagem'] => table.midiaImagem",
  "table[style-name='midiaVideo'] => table.midiaVideo",
  "table[style-name='secaoExperimentoteca'] => table.secaoExperimentoteca",
  "table[style-name='secaoJogosBrincadeiras'] => table.secaoJogosBrincadeiras",
  "table[style-name='secaoMaosNaMatematica'] => table.secaoMaosNaMatematica",
  "table[style-name='secaoProximaAula'] => table.secaoProximaAula",
  "table[style-name='secaoRodaGigante'] => table.secaoRodaGigante",
]

export default defaultStyleMap;
